### ISSUE TITLE
Change default branch to indigo

### ISSUE THREAD

**Issue by davetcoleman** [PR2/pr2_common#236]

**Comment by garaemon** [comment]
Why do we need different branch from hydro? I hope we can use same branch...

**Comment by UltronDestroyer** [comment]
Different distributions. Groovy had its own branch. Hydro does. Why not one for indigo devel?

**Comment by garaemon** [comment]
I think indigo works well with hydro codes without any changes.
If it's true in pr2_common repository, I think we don't need to have indigo-branch.

However, I agree with that it is reasonable to have different branches for each distribution. But it increases effort of maintainers...

**Comment by UltronDestroyer** [comment]
It's okay. I can deal with creating Indigo branches. If there is a bug that is only in Indigo, and someone fix it, but the release repository is pointing to Hydro, and then it breaks Hydro, then there will be problems.

Otherwise, any pull requests to Hydro branch will be forced to test against Hydro and Indigo. And logically, that would mean Hydro code would have to compile on 14.04 systems, and Indigo code against 12.04 systems..

**Comment by garaemon** [comment]
Great! It sounds perfect!

**Comment by davetcoleman** [comment]
1. There was already a indigo branch, it just wasn't default
2. I tried compiling this repo in indigo today and it was missing dependencies (ivcon and others)
3. urdfdom changed between distros so requires a split in branches

**Comment by UltronDestroyer** [comment]
This branch compiles and the stuff it requires has been released. Just has
to be installed via source ATM. I tested it last Tuesday.
